name: Checking Pull Request

on:
  pull_request:
    # Don't trigger if it's just a documentation/docker update.
    # We have separate build for checking docker updates.
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '**.yml'
      - '**.sh'
      - 'docs/**'
      - 'Dockerfile'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
      - '.dockerignore'
jobs:
  linux_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Initialize Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        pip install pytest pytest-cov bandit sphinx recommonmark
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Run CLI App
      run: |
        python cli.py --version