name: Checking Pull Request

on:
  pull_request:
    # Don't trigger if it's just a documentation/docker update.
    # We have separate build for checking docker updates.
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '**.yml'
      - '**.sh'
      - 'docs/**'
      - 'Dockerfile'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
      - '.dockerignore'
jobs:
  linux_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', 3.7', '3.8']
    steps:
    - uses: actions/checkout@master
    - name: Stup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x86
        cache: 'pip'
    - name: Install Pyinstaller
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    - name: Run CLI App
      run: |
        python cli.py --version